### ISSUE TITLE
Question on the need for app/templates.js

### ISSUE THREAD

**Issue by mrship** [j-mcnally/middleman-emblem#1]
I'm using your gem with a new middleman project and am confused over why the gem needs to write out all the .emblem templates to a separate app/template.js file. 

If I include my emblem templates folder into application.js with sprockets, i.e.:

``` js
//= require_tree ./templates
```

then all the .emblem files automatically get compiled into the served application.js anyway, although they do have the prefix of "templates/" in their name, i.e.:

``` js
Ember.TEMPLATES["templates/application"] = Ember.Handlebars.template(function anonymous(Handlebars,depth0,helpers,partials,data) {
this.compilerInfo = [2,'>= 1.0.0-rc.3'];
helpers = helpers || Ember.Handlebars.helpers; data = data || {};
  var buffer = '', hashTypes, escapeExpression=this.escapeExpression;

  hashTypes = {};
  data.buffer.push(escapeExpression(helpers._triageMustache.call(depth0, "outlet", {hash:{},contexts:[depth0],types:["ID"],hashTypes:hashTypes,data:data})));
  return buffer;

});
```

Do you write out app/template.js because the directory folder is appended to the template name by default? Is there a simple way to remove the folder prefix in the automatic compilation step, i.e. alter:

``` ruby
def template_target(scope)
  "Ember.TEMPLATES[#{scope.logical_path.inspect}]"
end
```

to remove the directory prefix somehow?

Thanks in advance for helping me deal with my confusion and for the gem.

**Comment by j-mcnally** [comment]
Honestly I don't have a good reason for any of it. When i was developing the compiler, i was kind of on my own and didnt really know what i was doing other than the fact that i wanted middleman to compile emblem templates which i couldn't do. I guess other build tools i had used before put all the templates into one file, so I just followed that pattern. Since the compiled templates aren't really editible after compilation I didn't see a huge need to keep them in seperate files. My method is just one way to do it, if you have a better solution I am happy to accept a PR.

**Comment by j-mcnally** [comment]
So if i understand you correctly we're saying rather than ignoring the templates and handling them ourselves, we could just register the sprocket extension and then middleman would send it through the pipleline itself?

**Comment by mrship** [comment]
Yes, in fact it does that already. You could remove all the code to write out app/templates.js. It also has the benefit that give the livereload built into Middleman it _does_ recompile the templates if you alter them.

The only question I have is how to remove the templates/ prefix to the template name. `ember-rails` allows for that with a configuration option - I'll have a look at how that works...

**Comment by j-mcnally** [comment]
o well that simple enough....

#{scope.logical_path.inspect}

in

```
  def template_target(scope)
    "Ember.TEMPLATES[#{scope.logical_path.inspect}]"
  end
```

is what would contain that.

**Comment by mrship** [comment]
Well, you still need to deal with subfolders though - I'm not sure calling `basename` will be enough. 

It's done with a [configuration option](https://github.com/emberjs/ember-rails/blob/master/lib/ember/handlebars/template.rb#L75-L91) in ember rails - that would be best.

**Comment by j-mcnally** [comment]
i can't seem to get the templates to build....

what am i missing here?

https://gist.github.com/j-mcnally/5521675

**Comment by mrship** [comment]
I've sent a PR with a fix that is working well for me - does it work for you?

**Comment by j-mcnally** [comment]
templates don't compile with this PR....

```
  create  build/app/templates/teams/conferences.emblem
  create  build/app/templates/games/game.emblem
  create  build/app/templates/games/conferences.emblem
  create  build/app/templates/teams.emblem
  create  build/app/templates/games.emblem
  create  build/app/templates/application.emblem
```

if we mainline this id like to be able to put templates under app

**Comment by mrship** [comment]
My templates _are_ under app. I ignore the source files when building as everything is in the application.js that will get built, i.e.

``` ruby
configure :build do
  # ignore the source files
  %w(controller models routes templates views).each do |dir|
    ignore "app/javascripts/#{dir}*"
  end
  #ignore the main Ember boot file
  ignore "app/javascripts/boot.js"
```

**Comment by j-mcnally** [comment]
can you show me an example of your pipeline file?

**Comment by mrship** [comment]
You mean middleman config.rb? if so - https://gist.github.com/mrship/5522044

**Comment by j-mcnally** [comment]
this makes almost no sense to me.

If you are ignoring the files how are they being built? i'd prefer to be verbose about things.

**Comment by mrship** [comment]
They're automatically compiled into the application js via sprockets. There's no need to copy them into a build folder.  By `//require`-ing all the files in application.js, i.e.:

```
//= require jquery
//= require handlebars
//= require ember
//= require ember-data
//= require ./boot
```

With boot.js being:

```
//= require_self
//= require_tree ./controllers
//= require_tree ./models
//= require_tree ./routes
//= require_tree ./templates
//= require_tree ./views

window.App = Ember.Application.create({
  Store: DS.Store.extend({
    revision: 11,
    adapter: DS.fixtureAdapter
  })
});
```

then the built application.js that gets copied to the build folder contains all you need.

**Comment by j-mcnally** [comment]
this doesnt work none of my templates are included.

**Comment by j-mcnally** [comment]
I am wrong it works. thanks!

**Comment by j-mcnally** [comment]
Thanks again for the help this is much better!

**Comment by mrship** [comment]
Happy to help, thanks for your quick responses on a Sunday!
